class Usdless < Formula
  desc "Terminal-based USD (Universal Scene Description) viewer"
  homepage "https://github.com/manorajesh/usdless"
  url "https://github.com/manorajesh/usdless/archive/refs/tags/v1.0.0.tar.gz"
  # Run: curl -L <url> | sha256sum   and paste the result here after tagging.
  sha256 "REPLACE_WITH_SHA256_AFTER_TAGGING_v1.0.0"
  license "MIT"

  head "https://github.com/manorajesh/usdless.git", branch: "master"

  bottle do
    # Bottles are generated by the CI after a pull-request to the tap lands.
    root_url "https://github.com/manorajesh/homebrew-usdless/releases/download/usdless-1.0.0"
  end

  depends_on "cmake" => :build
  depends_on "eigen"
  depends_on "usd"

  def install
    # Match the Python version that the usd formula was compiled against
    pxr_cfg = Formula["usd"].opt_lib/"cmake/pxr/pxrConfig.cmake"
    py_ver = pxr_cfg.read[/Python3? (\d+\.\d+)/, 1] if pxr_cfg.exist?
    py_ver ||= Formula["usd"].deps
                             .find { |d| d.name.start_with?("python@") }
                             &.name&.delete_prefix("python@")
    py_ver ||= Utils.safe_popen_read("python3", "--version").strip[/\d+\.\d+/]

    cmake_args = std_cmake_args + [
      "-DCMAKE_BUILD_TYPE=Release",
      "-Dpxr_DIR=#{Formula["usd"].opt_lib}/cmake/pxr",
    ]
    cmake_args << "-DPython3_VERSION=#{py_ver}" if py_ver

    system "cmake", "-B", "build", *cmake_args
    system "cmake", "--build", "build", "-j#{ENV.make_jobs}"
    system "cmake", "--install", "build"
  end

  test do
    assert_predicate bin/"usdless", :exist?
    assert_match "usdless", shell_output("#{bin}/usdless --help 2>&1")
  end
end
